# Generated by Django 4.1.3 on 2022-12-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicleDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_name', models.CharField(blank=True, max_length=25, null=True)),
                ('passengers', models.IntegerField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=25, null=True)),
                ('purpose', models.CharField(blank=True, max_length=25, null=True)),
                ('date', models.DateField(max_length=10)),
            ],
        ),
    ]
