# Generated by Django 4.1.3 on 2022-12-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=25, null=True)),
                ('item_unit', models.CharField(blank=True, max_length=25, null=True)),
                ('item_quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
