# Generated by Django 4.1.3 on 2022-12-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0002_vehicledb'),
        ('AuxiliaryApp', '0003_vehicledb'),
    ]

    operations = [
    ]
