# Generated by Django 4.0.1 on 2022-12-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='janitorDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_name', models.CharField(blank=True, max_length=25, null=True)),
                ('up_code', models.CharField(blank=True, max_length=4, null=True)),
                ('up_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=100, verbose_name='userType')),
            ],
        ),
    ]
