# Generated by Django 4.1.3 on 2022-12-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0004_merge_0002_vehicledb_0003_vehicledb'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledb',
            name='email',
            field=models.EmailField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='itemsdb',
            name='item_name',
            field=models.CharField(blank=True, choices=[('Round Rags', 'Round Rags'), ('Soft Broom', 'Soft Broom'), ('Stick Broom', 'Stick Broom'), ('Toilet Paper', 'Toilet Paper'), ('Garbage Bag', 'Garbage Bag')], max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='borrowDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janitor_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AuxiliaryApp.janitordb')),
            ],
        ),
    ]
