# Generated by Django 4.1.4 on 2022-12-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0005_vehicledb_email_alter_itemsdb_item_name_borrowdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledb',
            name='email',
            field=models.EmailField(default=None, max_length=300),
        ),
    ]
