# Generated by Django 4.1.4 on 2022-12-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0006_alter_vehicledb_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userType',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('RERAIR_MAN', 'REPAIR_MAN'), ('ASSISTANT_DIRECTOR', 'ASSISTANT_DIRECTOR')], max_length=100, verbose_name='userType'),
        ),
        migrations.AlterField(
            model_name='itemsdb',
            name='item_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='janitordb',
            name='up_status',
            field=models.CharField(default='ACTIVE', max_length=100, verbose_name='userType'),
        ),
    ]
