# Generated by Django 4.1.4 on 2022-12-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0007_alter_customuser_usertype_alter_itemsdb_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='historyDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('his_name', models.CharField(blank=True, max_length=50, null=True)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('his_form', models.CharField(blank=True, max_length=50, null=True)),
                ('his_date', models.DateField(max_length=10)),
            ],
        ),
    ]
