# Generated by Django 4.1.4 on 2022-12-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0008_historydb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydb',
            name='his_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
