# Generated by Django 4.1.4 on 2022-12-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0009_alter_historydb_his_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledb',
            name='status',
            field=models.CharField(default='PENDING', max_length=100, verbose_name='userType'),
        ),
    ]
