# Generated by Django 4.1.4 on 2022-12-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0010_vehicledb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historydb',
            name='his_status',
            field=models.CharField(blank=True, default='PENDING', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledb',
            name='status',
            field=models.CharField(default='PENDING', max_length=100, verbose_name='status'),
        ),
    ]
