# Generated by Django 4.0.1 on 2022-12-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0012_alter_historydb_his_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='borrowDB',
        ),
    ]
