# Generated by Django 4.0.1 on 2022-12-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0014_borrowdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='borrowDB',
        ),
    ]
