# Generated by Django 4.0.1 on 2022-12-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0020_remove_historydb_his_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainteDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_name', models.CharField(blank=True, max_length=25, null=True)),
                ('mp_status', models.CharField(default='ACTIVE', max_length=100)),
            ],
        ),
    ]
