# Generated by Django 4.1.3 on 2022-12-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0021_maintedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrepairdb',
            name='email',
            field=models.EmailField(default=None, max_length=300),
        ),
    ]
