# Generated by Django 4.1.3 on 2022-12-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0022_clientrepairdb_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsdb',
            name='itemsName_Quantity',
        ),
    ]
