# Generated by Django 4.1.3 on 2022-12-20 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0023_remove_itemsdb_itemsname_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='historydb',
            name='his_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AuxiliaryApp.borrowdb'),
        ),
    ]
