# Generated by Django 4.1.3 on 2022-12-20 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0024_historydb_his_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydb',
            name='his_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuxiliaryApp.borrowdb'),
        ),
    ]
