# Generated by Django 4.1.3 on 2022-12-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0025_alter_historydb_his_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historydb',
            name='his_id',
        ),
        migrations.AddField(
            model_name='historydb',
            name='borrow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AuxiliaryApp.borrowdb'),
        ),
        migrations.AddField(
            model_name='historydb',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AuxiliaryApp.vehicledb'),
        ),
    ]
