# Generated by Django 4.1.3 on 2022-12-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0026_remove_historydb_his_id_historydb_borrow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrepairdb',
            name='status',
            field=models.CharField(blank=True, default='PENDING', max_length=8),
        ),
    ]
