# Generated by Django 4.1.3 on 2022-12-20 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0027_alter_clientrepairdb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminrepairDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricate', models.CharField(choices=[(0, 'Can be Repaired/Fabricated in-house'), (1, "Can't be Repaired/Fabricated in-house")], max_length=100)),
                ('assess', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('assigned', models.CharField(blank=True, max_length=50, null=True)),
                ('prove', models.CharField(choices=[(0, 'APPROVED'), (1, 'DISAPPROVED'), (2, 'RESUBMIT REQUEST')], max_length=100)),
                ('head', models.CharField(blank=True, max_length=50, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuxiliaryApp.clientrepairdb')),
            ],
        ),
        migrations.CreateModel(
            name='mainterepairDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, max_length=50, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('inspect', models.CharField(blank=True, max_length=50, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuxiliaryApp.adminrepairdb')),
            ],
        ),
    ]
