# Generated by Django 4.1.3 on 2022-12-28 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0029_alter_adminrepairdb_fabricate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='returnclientDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitioner', models.CharField(blank=True, max_length=50, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('mainte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuxiliaryApp.mainterepairdb')),
            ],
        ),
    ]
