# Generated by Django 4.1.3 on 2022-12-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0031_alter_adminrepairdb_prove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrepairdb',
            name='fabricate',
            field=models.CharField(choices=[('YES', 'Can be Repaired/Fabricated in-house'), ('NO', "Can't be Repaired/Fabricated in-house")], max_length=100),
        ),
    ]
