# Generated by Django 4.1.3 on 2022-12-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0033_suppmatdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='approvalDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prove', models.CharField(choices=[('APPROVED', 'APPROVED'), ('DISAPPROVED', 'DISAPPROVED'), ('RESUBMIT REQUEST', 'RESUBMIT REQUEST')], max_length=100)),
                ('head', models.CharField(blank=True, max_length=50, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='adminrepairdb',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='adminrepairdb',
            name='head',
        ),
        migrations.RemoveField(
            model_name='adminrepairdb',
            name='prove',
        ),
    ]
