# Generated by Django 4.1.3 on 2023-01-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0035_approvaldb_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldb',
            name='optional',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
