# Generated by Django 4.1.3 on 2023-01-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0037_maintedb_mp_password_maintedb_mp_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintedb',
            name='userType',
            field=models.CharField(default='MAINTENANCE', max_length=100),
        ),
    ]
