# Generated by Django 4.1.4 on 2023-01-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0038_maintedb_usertype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mainteDB',
        ),
    ]
