# Generated by Django 4.1.4 on 2023-01-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuxiliaryApp', '0039_delete_maintedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=100, verbose_name='userType'),
        ),
    ]
